---

- name: Upgrading system
  apt:
    upgrade: "{{ apt_upgrade }}"
    update_cache: yes
    autoremove: "{{ apt_autoremove }}"
  when: (apt_upgrade == "safe") or (apt_upgrade == "full") or (apt_upgrade == "dist")
